"""Generated by tools/sync_text.py; edit acmanga/locales/en.json."""
TEXT = {'setup.an_unrelated_manga_cli_command_already_exists_refusing_to_overwrite_it': 'An unrelated '
                                                                                 'manga-cli '
                                                                                 'command already '
                                                                                 'exists; refusing '
                                                                                 'to overwrite it',
 'setup.bash_path_configured': 'Bash PATH configured for manga-cli. Open a new terminal, or run: '
                               'source ~/.bashrc',
 'setup.bash_path_not_changed': 'Could not safely update Bash PATH. Use the full command path or '
                                'add ~/.local/bin to PATH manually.',
 'setup.code_and_data_restored_from_the_backup': 'Code and data restored from the backup.',
 'setup.command': 'Command: ',
 'setup.do_not_use_sudo': 'Do not use sudo',
 'setup.integrity_check_failed': 'Integrity check failed: ',
 'setup.invalid_path_in_sha256sums': 'Invalid path in SHA256SUMS',
 'setup.manga_cli_installed_saved_manga_and_settings_were_not_modified': 'manga-cli 0.8.3 '
                                                                         'installed. Saved manga '
                                                                         'and settings were not '
                                                                         'modified.',
 'setup.manga_cli_uninstalled_saved_manga_settings_cache_and_backups_were_preser': 'manga-cli '
                                                                                   'uninstalled; '
                                                                                   'saved manga, '
                                                                                   'settings, '
                                                                                   'cache and '
                                                                                   'backups were '
                                                                                   'preserved.',
 'setup.mpv_is_missing_on_debian_sudo_apt_install_mpv': 'mpv is missing. On Debian: sudo apt '
                                                        'install mpv',
 'setup.mpv_with_gpu_or_x11_video_output_is_required': 'mpv with gpu or x11 video output is '
                                                       'required',
 'setup.open_a_new_terminal_or_run': 'Open a new terminal or run: ',
 'setup.previous_code_restored_current_saved_manga_and_progress_were_preserved': 'Previous code '
                                                                                 'restored. '
                                                                                 'Current saved '
                                                                                 'manga and '
                                                                                 'progress were '
                                                                                 'preserved.',
 'setup.private_backup': 'Private backup: ',
 'setup.python_3_8_or_later_is_required': 'Python 3.8 or later is required',
 'setup.run_bash_install_sh_as_your_own_user_without_sudo': 'Run bash install.sh as your own user, '
                                                            'WITHOUT sudo',
 'setup.sha256sums_is_missing_use_the_complete_release_zip': 'SHA256SUMS is missing: use the '
                                                             'complete release ZIP',
 'setup.the_manga_command_remains_as_a_compatibility_alias': 'The manga command remains as a '
                                                             'compatibility alias.',
 'setup.the_staged_copy_failed_its_self_test': 'The staged copy failed its self-test:\n',
 'setup.this_backup_belongs_to_another_home_automatic_restore_refused': 'This backup belongs to '
                                                                        'another HOME; automatic '
                                                                        'restore refused',
 'setup.to_restore_the_previous_code_while_keeping_your_current_progress': 'To restore the '
                                                                           'previous code while '
                                                                           'keeping your current '
                                                                           'progress:'}


def tr(key):
    return TEXT[key]
