#!/usr/bin/env python3
"""Regenerate standalone Lua/bootstrap messages from acmanga/locales/en.json."""
import argparse
import json
from pathlib import Path
import pprint
import re

ROOT = Path(__file__).resolve().parents[1]


def generated_files():
    messages = json.loads((ROOT / 'acmanga/locales/en.json').read_text(encoding='utf-8'))
    # JSON's quoted UTF-8 strings are also valid Lua strings for these messages.
    lua = 'local L = {\n' + ''.join(
        '    {} = {},\n'.format(key[4:], json.dumps(value, ensure_ascii=False))
        for key, value in sorted(messages.items()) if key.startswith('lua.')
    ) + '}\n'
    path = ROOT / 'acmanga/reader.lua'
    body = path.read_text(encoding='utf-8')
    body = re.sub(r'-- BEGIN GENERATED TEXT\n.*?-- END GENERATED TEXT',
                  lambda _: '-- BEGIN GENERATED TEXT\n' + lua + '-- END GENERATED TEXT',
                  body, count=1, flags=re.S)
    setup = {k: v for k, v in messages.items() if k.startswith('setup.')}
    bootstrap = ('"""Generated by tools/sync_text.py; edit acmanga/locales/en.json."""\n'
                 'TEXT = ' + pprint.pformat(setup, sort_dicts=True, width=100) + '\n\n\n'
                 'def tr(key):\n    return TEXT[key]\n')
    return {path: body, ROOT / 'tools/_messages.py': bootstrap}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail instead of writing stale files')
    args = parser.parse_args()
    stale = []
    for path, text in generated_files().items():
        if not path.exists() or path.read_text(encoding='utf-8') != text:
            stale.append(path.relative_to(ROOT))
            if not args.check:
                path.write_text(text, encoding='utf-8')
    if args.check and stale:
        print('Outdated generated text: ' + ', '.join(map(str, stale)))
        return 1
    print('Generated messages are up to date.' if args.check else 'Generated messages updated.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
